// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhAZs6MFFeb_jQogqw3FtMOvZq2gZuFeY',
    appId: '1:668771022671:web:a0362e402d08067d0ef73a',
    messagingSenderId: '668771022671',
    projectId: 'project-e2e46965-b75b-4e5e-82f',
    authDomain: 'project-e2e46965-b75b-4e5e-82f.firebaseapp.com',
    storageBucket: 'project-e2e46965-b75b-4e5e-82f.firebasestorage.app',
    measurementId: 'G-B14L7X78VH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv1uo9hs45WMO7R4LRtbh3QfWGDMySOzY',
    appId: '1:668771022671:android:aa7edbb232b98c660ef73a',
    messagingSenderId: '668771022671',
    projectId: 'project-e2e46965-b75b-4e5e-82f',
    storageBucket: 'project-e2e46965-b75b-4e5e-82f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTIx2gJn2o9A6bGgjws0Fyr1LjAGPJMaI',
    appId: '1:668771022671:ios:07bb8dc4890a05eb0ef73a',
    messagingSenderId: '668771022671',
    projectId: 'project-e2e46965-b75b-4e5e-82f',
    storageBucket: 'project-e2e46965-b75b-4e5e-82f.firebasestorage.app',
    iosBundleId: 'com.example.finTrackAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTIx2gJn2o9A6bGgjws0Fyr1LjAGPJMaI',
    appId: '1:668771022671:ios:07bb8dc4890a05eb0ef73a',
    messagingSenderId: '668771022671',
    projectId: 'project-e2e46965-b75b-4e5e-82f',
    storageBucket: 'project-e2e46965-b75b-4e5e-82f.firebasestorage.app',
    iosBundleId: 'com.example.finTrackAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhAZs6MFFeb_jQogqw3FtMOvZq2gZuFeY',
    appId: '1:668771022671:web:dd0f3aec73f1cd6b0ef73a',
    messagingSenderId: '668771022671',
    projectId: 'project-e2e46965-b75b-4e5e-82f',
    authDomain: 'project-e2e46965-b75b-4e5e-82f.firebaseapp.com',
    storageBucket: 'project-e2e46965-b75b-4e5e-82f.firebasestorage.app',
    measurementId: 'G-BZ0QRRF1P7',
  );
}
